### ISSUE TITLE
pyOCD basic_test.py fails on 2nd dev.open call on device with non-matching target id

### ISSUE THREAD

**Issue by mikew67** [mbedmicro/pyOCD#112]
**Synopsis:** Running basic_test.py on a new installation of pyOCD on a Mac, with an nRF51-DK connected, yields a "IOError: open failed" error.

**Scenario:**
**MacBook Pro, Core 2 Duo**
Mac OS X "Yosemite" 10.3.3 (pre-release seed 3)
Python 2.7.6
**Nordic nRF51-DK platform**
mbed IF: nrf51822aa_atsam3u2c_if_mbed_V0218_19022015.bin
Enumerates as: 
    Product ID:	0x0204
    Vendor ID:	0x0d28
    Version:	1.00
    Manufacturer:	MBED
**Backtrace on failure**
```
  File "basic_test.py", line 46, in <module>
    with MbedBoard.chooseBoard() as board:
  File "/Users/mwirth/Desktop/MacGitRepos/pyOCD/pyOCD/board/mbed_board.py", line 169, in chooseBoard
    all_mbeds = MbedBoard.getAllConnectedBoards(transport, False, blocking, target_override, frequency)
  File "/Users/mwirth/Desktop/MacGitRepos/pyOCD/pyOCD/board/mbed_board.py", line 122, in getAllConnectedBoards
    all_mbeds = INTERFACE[usb_backend].getAllConnectedInterface(mbed_vid, mbed_pid)
  File "/Users/mwirth/Desktop/MacGitRepos/pyOCD/pyOCD/interface/hidapi_backend.py", line 78, in getAllConnectedInterface
    dev.open(vid, pid)
  File "hid.pyx", line 48, in hid.device.open (hid.c:1263)
IOError: open failed
```

**Diagnostics:**
Original code snippet around dev.open call:
```
            try:
                dev.open(vid, pid)
            except AttributeError:
                pass
```
Added diagnostics:
```
            try:
                print "Getting ready to try dev.open"
                dev.open(vid, pid)
            except Exception, ex1:
                print "dev.open failed with exception: ", ex1
```
pyCharm debugger output:
```
pydev debugger: process 24017 is connecting

Connected to pydev debugger (build 139.1547)
Getting ready to try dev.open
INFO:root:Unsupported target found: 1100
INFO:root:Waiting for a USB device connected
Getting ready to try dev.open
dev.open failed with exception:  open failed

Process finished with exit code 139
```

**Analysis:**
So it looks like the dev.open is failing on the second pass, not the first (because the device is already open). On the first pass, it opens, but the code rejects the device later because the target id (1100) doesn't match.

I would suggest the following changes in the pyOCD code:
* Add 1100 to the set of matching target ids (Or fix how the id gets extracted from the nRF51-DK.)
* If the target id match fails (or the device is rejected for any other reason), make sure to close it.

**Comment by c1728p9** [comment]
Hi @mikew67 I have this branch to address your first point.  With this you should be able to get the nrf51-dk running: https://github.com/c1728p9/pyOCD/tree/nrf51-dk

**Comment by 0xc0170** [comment]
Thanks for reporting @mikew67 . As @c1728p9 pointed out, the other nrf chips were not added (their id is missing).

As I can see, there will be added soon :+1:

**Comment by c1728p9** [comment]
Hi @mikew67 , the pull request #110 fixed the problem where the same board is opened twice if it is unsupported.  The pull request #142 adds support for the nrf51-dk.  Can this issue be closed, or do you see any further problems?

**Comment by mikew67** [comment]
Yes, I'll close this.  Thanks for the followup.

Mike
