### ISSUE TITLE
The example in README need some modification to make it work

### ISSUE THREAD

**Issue by LiyouZhou** [mbedmicro/pyOCD#119]
The example in README need some modification to make it work

```
from pyOCD.gdbserver import GDBServer
from pyOCD.board import MbedBoard

import logging
logging.basicConfig(level=logging.INFO)

board = MbedBoard.chooseBoard()

# start gdbserver
gdb = GDBServer(board, 3333)

# ADD lines
# ====================================
while gdb.isAlive():
    gdb.join(timeout = 0.5)
# ====================================
```

**Comment by flit** [comment]
Closing this issue. The readme has been updated, and examples were moved to `docs/API_EXAMPLES.md` and updated. The gdbserver example code was removed because the `pyocd-gdbserver` tool is the canonical way to run pyOCD's gdbserver.
