### ISSUE TITLE
Failed "load" command on gdb_test.py

### ISSUE THREAD

**Issue by kaizen8501** [mbedmicro/pyOCD#161]
Hi
I added new target for W7500 of WIZnet MCU. And then I success automated_test.py on pyOCD.

## Get fail message when I enter load command on GNU gdb
After automated_test , I tried to test "gdb_test.py". connection is success to gdb server of pyOCD. But I got a fail message when issue "load" command. This picture is log message when I tested.
Left terminal in this picture is log message when I run gdb_test.py and right terminal is log message of GNU gdb.

<a href="https://www.flickr.com/photos/129944648@N04/18069527103" title="www.life4iot.com_007 by 동은 곽, Flickr에서"><img src="https://c1.staticflickr.com/1/381/18069527103_f054187216_o.png" width="1919" height="540" alt="www.life4iot.com_007"></a>

I want to know Why can't success after load command. If analyzer_supported is false in flash_w7500.py, Can't it use gdb for debugging W7500?

And How to solve this problem?

**Comment by c1728p9** [comment]
Hi @kaizen8501 , I would recommend using the gdb_server.py in pyOCD\tools.  The file gdb_test.py hasn't been updated in a while and might be out of date.  Also to add extra debug info you could use the "-d debug" argument in gdb_server.py.  

If that still doesn't work could you run the command "set remotelogfile pyocd.log" and then post the output of pyocd.log here?  That way I can see if there are any problems with the gdb communication.

Finally, does this problem only occur when analyzer_supported it set to true?

**Comment by kaizen8501** [comment]
Thank you @c1728p9 , As soon as I changed begin_data to 0x20002000 and analyzer_supported to "true", I solved this problem. So I can use load command of GNU gdb.

## Other Question

And then I tried to test using Eclipse IDE but I can't success as below picture.

<a href="https://www.flickr.com/photos/129944648@N04/18514231550" title="www.life4iot.com_009 by 동은 곽, Flickr에서"><img src="https://c1.staticflickr.com/1/419/18514231550_8ea1b44fb8_o.png" width="1919" height="1079" alt="www.life4iot.com_009"></a>

Do you know why did it happen? For more information, I attached my debug informtion on Eclipse.
<a href="https://www.flickr.com/photos/129944648@N04/18704298381" title="www.life4iot.com_010 by 동은 곽, Flickr에서"><img src="https://c1.staticflickr.com/1/461/18704298381_e326a577c4_o.png" width="1249" height="924" alt="www.life4iot.com_010"></a>

**Comment by c1728p9** [comment]
Glad I could help :smile:. The warning "Invalid mon command 'regs'" is expected since pyOCD does not support this command.  Eclipse doesn't seem to use this information and has better ways to retrieve regsiter data anyway.

The warning "Invalid mon command 'reset init'" is expected as well, but the command will probably be supported in the future.  As a simple workaround you could change the initial reset type to 'halt'.  This can be done in the 'Startup' tab of the 'WebSocket_WizFi250 OpenOCD' debug configuration.

As for the error at address 0xffffffff, this appreas to be from the program crashing, or a blank part.  You'll want to check that code was loaded correctly staring at address 0.  See if you can set a breakpoint early on in the boot sequence.

**Comment by kaizen8501** [comment]
Hi @c1728p9. I solved this problem as this document.
[http://www.life4iot.com/2015/06/15/how-to-use-gdb-on-eclipse-with-pyocd/?lang=en](http://www.life4iot.com/2015/06/15/how-to-use-gdb-on-eclipse-with-pyocd/?lang=en) <-- This is URL of my blog.

As a result, I can connect to gdb server of pyOCD from Eclipse IDE successfully.

Additionally, I have one question. I heard that mbed web compiler will support debugger function next plan. I think pyOCD will be included on mbed web compiler. Is it right?

Thank you.

**Comment by c1728p9** [comment]
Good to hear you got things working.  Cool blog, I like that you are sharing information about pyOCD :smiley:.  I'm not sure on plans for web debugger support.  @0xc0170 ,do you have any details on this that can be shared?

**Comment by 0xc0170** [comment]
I'll close this as it's resolved.

@c1728p9 I am not familiar with the plans for this future.
