### ISSUE TITLE
Does pyOCD have a mailing list?

### ISSUE THREAD

**Issue by tgarc** [mbedmicro/pyOCD#191]
I'd like to contribute, but I couldn't find any documentation on the matter. Is there any mailing list or groups that I could subscribe to to stay updated on discussions of pyOCD development?

**Comment by 0xc0170** [comment]
We have mbed-devel mailing list where you could find some old discussions, but mostly just notifications from github. 

Github might be the best place for this. The discussions are mostly here, in pull requests or issues.
