### ISSUE TITLE
BUG: `chooseInterface` function does not exist

### ISSUE THREAD

**Issue by tgarc** [mbedmicro/pyOCD#192]
I noticed in the `Board` class that there is some interface initialization code that refers to a function called `chooseInterface` that is currently not part of the code base. Here is the relevant piece:

```python
class Board(object):
    """
    This class associates a target, a flash, a transport and an interface
    to create a board
    """
    def __init__(self, target, flash, interface, transport="cmsis_dap", frequency=1000000):
        if isinstance(interface, str) == False:
            self.interface = interface
        else:
            self.interface = INTERFACE[interface].chooseInterface(INTERFACE[interface])
```

I'm guessing this function just got taken out of the code at some point and was replaced with something else (`MbedBoard.chooseBoard`?).

**Comment by c1728p9** [comment]
Thanks for reporting.  Looking at the blame for that change, it looks like it was there from the beginning of the project and was a bug when it was checked in.  Feel free to open a PR to fix this if you have time.  Otherwise I'll remove it some time in the future.

**Comment by 0xc0170** [comment]
PR welcome!

**Comment by tgarc** [comment]
OK, will submit that soon
