### ISSUE TITLE
Using websockets is not clear in pyocd-gdbserver

### ISSUE THREAD

**Issue by 0xc0170** [mbedmicro/pyOCD#203]
I noticed today looking at the websocket support, that gdbserver provides port (-p) argument which as help says it's for port. But looking at the code, it is not just a port, it can be url address for websockets, code reference: https://github.com/mbedmicro/pyOCD/blob/master/pyOCD/gdbserver/gdbserver.py#L220

Connects #460

**Comment by flit** [comment]
Yes, I've wondered about this, too. Was it intended to support debugging via the online IDE? I carried over the websocket support to semihosting just in case.

**Comment by 0xc0170** [comment]
> Was it intended to support debugging via the online IDE?

I would guess yes.

 we are currently playing with this websockets, we might share more soon

**Comment by jupe** [comment]
This should be documented, and if there is some experimental features it is ok as long as its documented so.

**Comment by flit** [comment]
Websocket support will be removed in a future version.

**Comment by flit** [comment]
Closing since websocket support was removed in #551.
