### ISSUE TITLE
Python 3 compatible

### ISSUE THREAD

**Issue by 0xc0170** [mbedmicro/pyOCD#208]
We should make pyOCD compatible with python 3.

**Comment by ntoll** [comment]
Yes, absolutely this.

**Comment by Machine-Hum** [comment]
Is there an update on this?

**Comment by flit** [comment]
@Machine-Hum @ntoll We're starting to work on it! The goal is to have Python 3 support by the end of this year. (There are a lot of other great features coming, too.)

**Comment by flit** [comment]
Ok, the PR to add Python 3 support is now ready for testing: #374! Please try it out and report any issues you run into. All test cases pass, but I'd like to get some direct feedback from users.

**Comment by Machine-Hum** [comment]
WOOT!

**Comment by flit** [comment]
[Version 0.11.0](https://github.com/mbedmicro/pyOCD/releases/tag/v0.11.0) of pyOCD is now released with the Python 3 support, so you can update via pip.

Since Py3 support is official now, I'm closing this issue. If you do run into any problems, please create new issues. Thanks!
