### ISSUE TITLE
Eclipse OpenOCD Debugging plug-in expects ``mon reg`` cmd

### ISSUE THREAD

**Issue by tgarc** [mbedmicro/pyOCD#217]
I noticed that the OpenOCD Debugging plug-in for Eclipse issues a ``mon reg`` on starting a debugging session. I'm guessing this is the reason for the no-op reg command that was originally present in the source but removed by my last PR. This isn't high priority - I'm not sure yet how it effects debugging in Eclipse - I just wanted to document it.

Related to PR 211: https://github.com/mbedmicro/pyOCD/pull/211

**Comment by c1728p9** [comment]
Thanks for opening an issue to investigate this further.  I have been using Eclipse with the OpenOCD plugin after #211 and haven't seen any problems.  @flit , do you know what the mon reg command is used for, if anything?

**Comment by flit** [comment]
Afaik, the only purpose for the "reg" command is to dump register values. I'm pretty sure it doesn't hurt compatibility with the OpenOCD plugin if it is not implemented.

**Comment by c1728p9** [comment]
Closing this issue since it isn't a problem.  If it becomes one please re-open.
