### ISSUE TITLE
pyOCD developer set-up doesn't work with Python 2.7

### ISSUE THREAD

**Issue by ntoll** [mbedmicro/pyOCD#271]
Hi,

Followed the README verbatim. I had to install nose by hand (shouldn't this be in the `dev-requirements.txt`?). Ran the tests and get...

```
Ran 40 tests in 0.161s

FAILED (errors=25)
```

Either the test suite needs fixing or setup instructions are borked. :-(

N.

**Comment by flit** [comment]
pytest is in `dev-requirements.txt`. It is required instead of nose. We just need to update the readme to use py.test instead of nosetests.

**Comment by Hsiangkai** [comment]
I have updated README.rst in https://github.com/mbedmicro/pyOCD/pull/330.
Please help me to review it. I tried these test commands in my local machine.

**Comment by flit** [comment]
Closing. Developer setup has been updated in the docs/DEVELOPERS_GUIDE.md.
