### ISSUE TITLE
Target Support EFM32

### ISSUE THREAD

**Issue by pfried** [mbedmicro/pyOCD#280]
What are the steps to support a new platform? We do have several boards here and some are supported by pcOCD, some are not.

E.g. our EFM32 boards by Silicon labs are not supported.

How much effort is it to add support for this platform? How could one provide the support?

**Comment by moyoumos** [comment]
+1

**Comment by c1728p9** [comment]
Hi @pfried, do the EFM32 devices you mention have support in a cmsis-pack? If so, support for this target may come in with #284.

**Comment by c1728p9** [comment]
@flit can you provide any information on when pack targets will be supported?

**Comment by flit** [comment]
Hi @pfried, we typically rely on silicon partners and community members to add support for new targets. For broader target support, we are going to be moving to a CMSIS-Pack based configuration system (in addition to the existing built-in targets). The issue tracking this is #357. The goal is to have this completed by March 2019 (work has started).

**Comment by pfried** [comment]
I think we will wait for a pack support. For our current development we "solved" this issue by using the Segger J-Link Server for gdb debugging.

**Comment by flit** [comment]
Fyi, version 0.16.0 added pack support. You can download a pack from http://www.keil.com/dd2/pack/ and use the `--pack` command line argument to make the devices it defines available to pyOCD.

**Comment by pelrun** [comment]
Can confirm this works with the EFM32G pack downloaded from https://developer.arm.com/embedded/cmsis/cmsis-packs.

**Comment by flit** [comment]
Excellent, thanks for reporting your success!

**Comment by flit** [comment]
Closing this issue since EFM32 targets are now supported via CMSIS-Packs.

With version 0.19.0, you can now add EFM32 support just by running `pyocd pack -i efm32`. That will install quite a few packs, so you probably want to be more specific about the part number.

**Comment by pfried** [comment]
@flit about the installation of the packs: Do I then have to specify the full pack path for the commands or is there a name shortcut for the argument or are the recognized globally and if I specify a target it matches with the pack?
