### ISSUE TITLE
starting gdb server with port 0 doesn't print actual port in use

### ISSUE THREAD

**Issue by jupe** [mbedmicro/pyOCD#299]
## Description
I want to start multiple gdb servers parallel. Now only way is to detect free port before calling `pyocd-gdbserver` because if I use `-p 0` it doesn't give me actual port number in use.

## How to reproduce
run gdb server
```
$ pyocd-gdbserver -p 0
...
INFO:root:GDB server started at port:0
```
pyocd is running now but it just print `..port:0` -which are not valid. See below:

```
$ lsof -iTCP -sTCP:LISTEN
COMMAND     PID     USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Python    13091 jva    3u  IPv4 0x73fd86420b3627b3      0t0  TCP localhost:krb524 (LISTEN)
Python    13091 jva    4u  IPv4 0x73fd86420b36f7b3      0t0  TCP localhost:51418 (LISTEN)
```

**Comment by jupe** [comment]
any chance to implement this. This blocks test beds integration... 
cc: @studavekar @kjbracey-arm

**Comment by kjbracey-arm** [comment]
Would you care to test #455?
