### ISSUE TITLE
udev rule required for non-root use on linux

### ISSUE THREAD

**Issue by mogenson** [mbedmicro/pyOCD#312]
Tools such as pyocd-flashtool require root privilege to access connected CMSIS-DAP debuggers.
``` 
$ pyocd-flashtool -l
No available boards are connected
$ sudo pyocd-flashtool -l
0 => Microbit [nrf51] boardId => 9900000037024e45001b200f000000320000000097969901
```
This is inconvenient when used in a build system that sets environmental variables for a non-root user. It would be helpful to have a section in the installation instructions about udev rules. For my hardware, the following rule grants access to members of the `plugdev` group.
```
ACTION=="add", SUBSYSTEMS=="usb", ATTRS{idVendor}=="0d28", ATTRS{idProduct}=="0204", MODE="660", GROUP="plugdev"
```

pyOCD (0.8.1a1) - Ubuntu 16.04.2 - x86_64

**Comment by flit** [comment]
Closing this issue. The readme has been updated with information about udev rules, and an example udev rule file is included (`udev/50-pyocd.rules`).
