### ISSUE TITLE
Problem with using on frdm-K64F

### ISSUE THREAD

**Issue by masoudr** [mbedmicro/pyOCD#313]
Hi,
I'm trying to use pyOCD to run a debug server, but when I want to start it with `pyocd-gdbserver` or `pyocd-gdbserver -t k64f` but the same error comes up.
```
C:\Windows\system32>pyocd-gdbserver
uncaught exception:
Traceback (most recent call last):
  File "build\bdist.win32\egg\pyOCD\tools\gdb_server.py", line 298, in run
    frequency=self.args.frequency)
  File "build\bdist.win32\egg\pyOCD\board\mbed_board.py", line 262, in chooseBoard
    mbed.link.open()
  File "build\bdist.win32\egg\pyOCD\pyDAPAccess\dap_access_cmsis_dap.py", line 513, in open
    self._interface.open()
  File "build\bdist.win32\egg\pyOCD\pyDAPAccess\interface\pywinusb_backend.py", line 93, in open
    assert False
AssertionError
```
Here is the version and board id:
```
C:\Users\Masoud>pyocd-gdbserver -l
0 => FRDM-K64F [k64f] boardId => 0240000034544e45005100028aa900352011000097969900

C:\Users\Masoud>pyocd-gdbserver --version
0.8.1a2.dev38
```
Thanks.

**Comment by flit** [comment]
This is the section of code containing the assert:
```py
            if time() - start > OPEN_TIMEOUT_S:
                # If this timeout has elapsed then another process
                # has locked this device in shared mode. This should
                # not happen.
                assert False
                break
```

This comment suggests that you have another process that is trying to use the board.

@c1728p9 Is this a valid interpretation?

**Comment by c1728p9** [comment]
Yep @flit, that is correct. Furthermore, it isn't another instance of pyOCD locking the board since it opens it for exclusive access rather than shared access.

**Comment by masoudr** [comment]
Thanks for the answers.
But how can I solve it ? I'm using `mbed-cli` to compile and upload to the board or `online compiler`.

**Comment by flit** [comment]
Closing old issue.
