### ISSUE TITLE
New target: MAX32630FTHR

### ISSUE THREAD

**Issue by AlexFroio** [mbedmicro/pyOCD#338]
I've been messing around trying to get a debugger working with this board and came across pyOCD. Although it is unsupported, pyOCD manages to recognize what the debugging hardware can do.

```WARNING:root:Unsupported board found 0409
INFO:root:DAP SWD MODE initialised
INFO:root:ROM table #0 @ 0xe00ff000 cidr=b105100d pidr=4000bb4c4
INFO:root:[0]<e000e000:SCS-M4 cidr=b105e00d, pidr=4000bb00c, class=14>
WARNING:root:Invalid coresight component, cidr=0x0
INFO:root:[1]<e0001000: cidr=0, pidr=0, component invalid>
INFO:root:[2]<e0002000:FPB cidr=b105e00d, pidr=4002bb003, class=14>
INFO:root:CPU core is Cortex-M4
INFO:root:FPU present
INFO:root:6 hardware breakpoints, 4 literal comparators
INFO:root:4 hardware watchpoints
INFO:root:Telnet: server started on port 4444
INFO:root:GDB server started at port:3333
```

I've paired this up with a custom setup in PlatformIO, and managed to get a connection to the board, but no stack trace. Is it possible to add support for this device? It is a CMSIS-DAP based board with a SWD interface for flashing to it.

[https://os.mbed.com/platforms/MAX32630FTHR/](https://os.mbed.com/platforms/MAX32630FTHR/ )
^This is the board.

**Comment by flit** [comment]
Closing this issue. The MAX32630 is now supported in pyOCD thanks to contributions from Maxim.
