### ISSUE TITLE
Unsupported board max32625pico - 0409

### ISSUE THREAD

**Issue by frank9876** [mbedmicro/pyOCD#341]
WARNING:root:Unsupported board found 0409
The max32625pico is not supported in the board types.

**Comment by flit** [comment]
The MAX32625 is not a supported target, nor is the max32625pico board. We welcome pull requests to add new boards and targets.

**Comment by flit** [comment]
According to Maxim, the correct board ID for the MAX32625PICO is actually 0416.

**Comment by flit** [comment]
Closing issue. MAX32625 support was added in #524.
