### ISSUE TITLE
Question: How-to add new board support documentation? Interested in the Peach.

### ISSUE THREAD

**Issue by g40** [mbedmicro/pyOCD#348]
Is there any? I'm rather keen on getting pyOCD working with an mbed-enabled Renesas RZA1 board (Peach). Is anyone working on said target?

TAIA.

**Comment by Hoohaha** [comment]
why nobody give some feedback?

**Comment by flit** [comment]
There is currently no specific documentation for adding a port. Improving documentation is one of the top items on the list.

**Comment by flit** [comment]
Closing. Documentation for adding new targets was added in `docs/ADDING_NEW_TARGETS.md`.
