### ISSUE TITLE
Board listing improvements on Windows

### ISSUE THREAD

**Issue by schuschu** [mbedmicro/pyOCD#379]
While #336 adds colorama support for fancy output (on *nix), colorama.init() should be called first to also support Windows.

**Comment by flit** [comment]
@schuschu Thanks for the bug report, this will get fixed in a v0.11.1 release that is coming up shortly.

**Comment by flit** [comment]
@schuschu pyOCD v0.11.1 was just released with a fix for this issue. Thanks again for the bug report!

Closing this issue.
