### ISSUE TITLE
Flash algorithm for LPC54608 may not be erasing upper half of the flash

### ISSUE THREAD

**Issue by maclobdell** [mbedmicro/pyOCD#410]
We recently found a bug in the flash algorithm for this device in DAPLink in which the upper 256K of flash was not getting properly erased before being programmed.  Need to evaluate the flash algo used by pyOCD to confirm if the same problem exists.

**Comment by maclobdell** [comment]
See issue https://github.com/ARMmbed/DAPLink/issues/501

**Comment by flit** [comment]
Closing issue as it was fixed.
