### ISSUE TITLE
Please rename the repository to use a lowercase module name.

### ISSUE THREAD

**Issue by codehelp** [mbedmicro/pyOCD#411]
To be able to package pyocd for distributions, the tarball produced by `python3 setup.py sdist` needs significant mangling to remove the binary files which have no source and to rename the entire directory to lowercase only.

Please can the pyOCD directory be renamed to lowercase?

Please can the binaries and elf files not be included in the release?

**Comment by flit** [comment]
Hi @codehelp. Thanks for raising these issues. And my apologies in advance, I know nearly nothing about Debian packages.

Why can't binaries be included in the package? The binaries are required for the automated functional tests (`test/` directory). How do other Python packages that have binaries such as executable or shared libraries within the Python package deal with this?

Renaming the main pyOCD package to all lowercase is already included for discussion in the list of things to possibly fix for cleaning up the API naming conventions. But it would be a big breaking change, and no decision has been made yet. (I'm in favour of it. Good to hear this feedback from the community.)

But I'm curious why an all lowercase name is required when packaging? And how that affects users since code would not be compatible with pyOCD installed via pip, etc.

cc @c1728p9 @sg-

**Comment by codehelp** [comment]
The most important problem, for me, with the binaries in the git source tree is simply this: **Why should I trust these binaries?** Just because they exist in a git source tree tells me nothing about how safe it is to run those binaries on my system. I have no reason to trust random binaries on github - indeed I have every reason to not trust them simply because it is github - the wild west of source code.

All the files in a binary Debian package in the main archive must be completely built solely from the source code of that package (without going off to the internet to get mystery blobs). Currently, the presence of the binaries means that I have to build packages just for Linaro and I can't use the normal Debian infrastructure to build and distribute the package. The current pyocd package could go into "non-free" in Debian but that isn't a good place to be, packages are not automatically built on upload, some users don't enable it and it doesn't reflect the actual licensing of the pyocd source code.

I'm not aware of other Python packages which have prebuilt binaries within the source code. Normally, a python package which is a binding for a shared library will simply depend on the shared library although pypi is unable to cope with such things. The shared library would already exist, built from it's source code, as a separate source package. 

Alternatively, the source package providing the shared library can also provide a python binding, as Guest FS does: https://tracker.debian.org/pkg/libguestfs - python3-guestfs is built from the same source code that builds the libguestfs0 shared library. (Note that python packages which depend on the python bindings from GuestFS also cannot use pypi because pypi has no understanding of non-pypi dependencies. Not all python code can live in pypi.)

Equally, it's not good for contributors to pyocd to come across mysterious binaries in a git source tree. Git isn't efficient at handling binaries, contributors know nothing about the providence of those binaries and there are risks to running binaries for which the source code is not available. pyocd isn't just about developer boxes and developer machines. People are trying to use pyocd in a production environment - admins get very upset with binary files of unknown providence causing an unknowable risk. Does pyocd even check the integrity of the binaries before glibly using them? Just because they exist in a particular filesystem path is no guide to the security or integrity of these mysterious blobs. There is a security hole worthy of a CVE right there, ready and waiting.

There are other ways of running automated tests - as it is the pyocd packages will not run the current tests anyway. I simply cannot trust the binaries in the git tree. A better solution would be to provide these in a Docker with clear traceability of how the original files were built (by providing logs of the build of the binaries, e.g. inside another docker) so that the community can have some assurance of what is intended to be in those binaries. Publish sha256sums of the built files, show that those checksums are checked when the binaries are installed into their own docker and again when the binaries are used by pyocd - everytime they are used by pyocd.

If pyocd wants to retain these binaries, I would suggest:

1. Build the binaries in a docker image and publish the full build logs as well as the docker image, for reproducibility.
1. During the build, create sha256sum (MD5sum optionally too) checksums of all binaries which are to be used later. Publish those checksums alongside the docker image.
1. Cryptographically sign the checksum files (just as distributions sign their checksum files on the mirrors). Publish the fingerprint of the key so that the community can verify the signatures themselves. Otherwise, the checksum files are no more trustworthy than the existing binaries.
1. Build a second docker image which pulls in these binaries and checks the checksums and verifies the cryptographic signature on the checksum files. This docker is then used for the automated tests and contains at least a README, preferably the complete build log, with links back to the first docker image and instructions on how to rebuild that first docker and how to verify the binaries.
1. **Every** time pyocd accesses these binary files, it must verify the files against those checksums and fail noisily if anything is wrong. (Just as admins can verify the files provided from packages by checksums in case of a security intrusion.)
1. pyocd gets renamed and added to Debian with no binaries in github but with documentation on how to run the automated tests using docker.

As for renaming the binary, this is simply Debian Policy and there is no prospect of changing this for a little package like pyocd. Other packages all use lowercase, even big projects like PostgreSQL and GuestFS. This isn't just Debian, other distributions have similar policies.

Overall, it would be a big change but it is a change which helps community usage of pyocd. For now, pyocd is a pain to handle because I have to both remove the security risk binaries and I have to rename the files in the tarball produced by `python3 setup.py sdist` or downloaded from a git tag. I then have to build it manually and provide infrastructure to host the binaries outside Debian. That all adds delays to the process of testing and deploying new versions of pyocd in production labs to do CI on IoT devices.

Renaming the directory doesn't affect users that badly, it's not as if pyocd gets imported into other python libraries or scripts - most users simply call the scripts (which are already lowercased) like /usr/bin/pyocd-flashtool.

(I realise now this would have been easier if I'd filed two separate issues).

**Comment by flit** [comment]
Please keep in mind that these are firmware binaries that run on a microcontroller dev board, not on a host system. It's a very different context, and there is little to no value from any attack. However, I understand the concerns with binaries that have no provenance. We will discuss internally what mitigations may be possible. (I'll also digest your suggestions more thoroughly once we get past demands related to TechCon.) Thanks.

**Comment by flit** [comment]
Btw, you realize that the flash algos for each of the target MCUs (under `pyOCD.target.*`) are another set of binaries? They happen to be stored as int lists in the Python code, but could just as easily be .bin files accessed as package resources. Same threat scope as the test binaries. But the flash algos are required for pyOCD to be able to perform one of its key functions, programming target flash.

In the near-term, we will be moving to using CMSIS-Packs as the primary target support vehicle. CMSIS-Packs contain flash algos in .FLM files, which are simply binary ELF files with a different extension. Users will download Packs using one of the various Pack Manager tools (Keil, IAR, GNU MCU Eclipse, etc), then pyOCD will read the .FLM file(s) from the Pack.

**Comment by codehelp** [comment]
The flash algos in `target/` like `target_CC3220SF.py` are fine as source code - these are target-specific references and addresses which only make sense as static data. The data is presented in a form which allows modification and that is what matters. These are included in the package. The files in `binaries/` is not included in the package, neither are the files in `elf_files`.

I understand about the firmware binaries being for separate boards, the difference in context is familiar from issues I have with scripts destined to run on a DUT but packaged in LAVA.

I've tried experimenting with simple changes to MANIFEST.in but setuptools insists on always including `binaries/` and `elf_files/` into the tarball coming from ``python3 setup.py sdist``. Whilst it is acceptable (for distribution & packaging) to remove these binaries from the tarball of the pyocd release, I do see that it would not make sense to remove these entirely or put these into a separate git repo for "pyocd-data" as that would be too much of a barrier for running the pyocd tests upstream. As it is, the pyocd tests won't be able to run on the packaged pyocd. That isn't a problem, it's just inevitable in how pyocd needs to operate. I can set the Debian CI to add the upstream git repo to the packaged code and then run the tests.

So, I'll repackage each released tarball to drop `binaries/` and `elf_files/` directories, that's an extra step in the packaging but is do-able. I'll drop the request to remove those directories from the released tarball.

It would still be nice to rename the `pyOCD` directory to `pyocd` at some point. I'll rename the description of this issue.

**Comment by flit** [comment]
Closing, as #433 renamed the pyOCD package to `pyocd`.
