### ISSUE TITLE
Remove websockets

### ISSUE THREAD

**Issue by flit** [mbedmicro/pyOCD#460]
It appears nobody is using websockets anymore. It should be removed to reduce complexity.

**Comment by cederom** [comment]
Never used that before @flit but wouldn't that may come handy with DAPLink + WebUSB work of @arekzaluski to create a web based debugger? :-)

**Comment by arekzaluski** [comment]
@cederom We were indeed using pyOCD with websockets in the past. @flit To my knowledge it is not used anymore and can be safely removed. We fully switched to use WebUSB instead.
