### ISSUE TITLE
requirements: versioning being more strict

### ISSUE THREAD

**Issue by 0xc0170** [mbedmicro/pyOCD#477]
Follow up from https://github.com/mbedmicro/pyOCD/pull/476. We experienced how easy is to break the chain of modules that depend on pyOCD.

We should not fetch any major version (at least major, not certain how strict we want to be) without testing first. Good example in 476.

**Comment by cmonr** [comment]
For reference, this is what Mbed OS does: https://github.com/ARMmbed/mbed-os/blob/master/requirements.txt
