### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 6075: illegal multibyte sequence

### ISSUE THREAD

**Issue by 392625227** [mbedmicro/pyOCD#505]
C:\Users\Administrator\Desktop\pyOCD-master\pyOCD-master>pip install -U pyocd
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pyocd
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/6c/ae/0baea35a5d061315af00b4b461efa9f1f0c897017230442939f18e9e6
885/pyocd-0.14.3.tar.gz (1.0MB)
    100% |████████████████████████████████| 1.0MB 2.4MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-fnllq72b\pyocd\setup.py", line 31, in <module>
        long_description=open('README.md', 'r').read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 6075: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-fnllq72b
\pyocd\

**Comment by flit** [comment]
Fixed in #495.
