### ISSUE TITLE
dapTransfer fails on an erased chip

### ISSUE THREAD

**Issue by tkuyucu** [mbedmicro/pyOCD#51]
After doing a full chip erase (either by calling board.flash.eraseAll() or by other means), pyocd is unable to communicate with the boards.  An operation such as board.flash.init()  will  either hang or casue a "SWD fault" in the function dapTransfer of cmsis_dap_core.pyc

Tested on nrf mkit and freescale kl25z boards.

**Comment by c1728p9** [comment]
Pull request #142 should fix further programming problems.  Has anyone seen this problem lately?  I erased both an nrf51 and k22f and was able to reconnect and program them without any problems.  I also ran blank_test.py on both, which continuously erases and resets the boards and the test found no problems.  I think this issue can be closed.
