### ISSUE TITLE
STLink devices not recognized on windows

### ISSUE THREAD

**Issue by jarlamsa** [mbedmicro/pyOCD#536]
I am unable to recognize devices using STLink on Windows.
I added support for STM32F429ZI, working on Linux after adding the udev rules.

Changes made on top of 5e056ceb064a7820bebb46d4987c206733984990

Device is working with OpenOCD on windows and can be found with mbedls.

**Comment by bridadan** [comment]
Hi @jarlamsa, did you follow the steps for installing libusb on Windows? https://github.com/mbedmicro/pyOCD#libusb-installation

**Comment by jarlamsa** [comment]
Good note, how could I miss that. Thank you.
