### ISSUE TITLE
ModuleNotFoundError: No module named 'pyocd._version'

### ISSUE THREAD

**Issue by CharlesChenArm** [mbedmicro/pyOCD#584]
window 10, board:NUCLEO_F429ZI
when run python basic_test.py in pyOCD/test directory, it will give a hint as follows:
![image](https://user-images.githubusercontent.com/46553263/54731231-11760380-4bc8-11e9-9594-c504a1610e20.png)
work around:
add -version.py in pyOCD\pyocd directory.
the content of -version.py is "version='0.18.0'", the version number is the version of my machine.

**Comment by Hoohaha** [comment]
@CharlesChenArm 

Run command `pip install -r requirements-dev.txt` to install pyocd in development mode. 
Maybe it can help you.

**Comment by CharlesChenArm** [comment]
@Hoohaha 
I try your way, but it doesn't work.
![image](https://user-images.githubusercontent.com/46553263/54734843-8142b900-4bdd-11e9-855b-cfde4f299bc7.png)

**Comment by Hoohaha** [comment]
@CharlesChenArm 
I am sorry, the correct file name should be `dev-requirements.txt`

**Comment by CharlesChenArm** [comment]
@Hoohaha  it can work, thank you:)

**Comment by flit** [comment]
Can this issue be closed?

@Hoohaha Thanks for your help!!

**Comment by CharlesChenArm** [comment]
@flit 
Does this solution need to add to our documents?  It is just a suggestion for your reference before closing it:)

**Comment by Hoohaha** [comment]
@CharlesChenArm 

https://github.com/mbedmicro/pyOCD/blob/master/docs/developers_guide.md#steps

**Comment by CharlesChenArm** [comment]
@Hoohaha  Thank you very much. This issue can be closed:)
