### ISSUE TITLE
Attribute or syntax errors while making test on new board added.

### ISSUE THREAD

**Issue by rgf97** [mbedmicro/pyOCD#625]
Hi :), When I make test on a new board added, i get attribute or syntax error like this:

![image](https://user-images.githubusercontent.com/45605957/56581637-ac05a000-65d5-11e9-8ea9-966bd528d1a6.png)

What is wrong?

**Comment by flit** [comment]
You need to set the target type. Either use the `--target` command line argument, or `target_override` user option (best set in a `pyocd.yaml` config file). When running the functional tests you have to use a config file (in the `test/` directory) to set the target type, as well as set the `test_binary` option (set to just the name, not a path, of a file in the `binaries/` directory).

You can check the `Target type is x` log message to verify which target pyOCD is using. If no target type is set it will default to "cortex_m", which doesn't have flash support or a memory map.

**Comment by rgf97** [comment]
I had already done that. but i named the .yaml file "test_boards" instead of "pyocd". Rename the file to pyocd solved the problem. Thank you @flit .

**Comment by flit** [comment]
Is "test_boards.yaml" still mentioned in the docs? I checked, but could easily have missed it.

**Comment by rgf97** [comment]
No, it is not mentioned in this docs. I did not use this docs. But i saw the same thing in a past issue solutions. And there, it was indicated to use a test_boards.yaml. 
Honestly, i thought the file name did not matter.

**Comment by flit** [comment]
Well, originally it _was_ "test_boards.yaml". But when I added general config file support via "pyocd.yaml", I changed the functional tests to use that so there was only one config file name.
