### ISSUE TITLE
Flash: LPC targets - flash blob - erase sector

### ISSUE THREAD

**Issue by 0xc0170** [mbedmicro/pyOCD#67]
#63  - a new feature requires to have erase sector available in flash blob. Kinetis devices already provide it, LPC should as well.

**Comment by c1728p9** [comment]
I think this issue can be closed now.  The commits 7aad94c4f6f820d7a83d9710288102a49bbcd1b3 and  99d2b8f068da52c485bef2c49c76639582be494c should have taken care of this.
