### ISSUE TITLE
memoryMap bound to class creates concurrency issues

### ISSUE THREAD

**Issue by ingeryp** [mbedmicro/pyOCD#694]
There is an issue where, when you have created multiple boards of the same type and try to flash/erase them in parallel you get concurrency issues.

This is in some part due to the fact that the MemoryMap for the targets are bound to the class rather than the instance. This means that associated FlashRegions are not unique per board instance and these have some mutating state in which you get pretty reliable race-conditions.

This was verified by overloading the builtin targets and moving MemoryMap() to __init__. It would be better to have this problem fixed in pyocd though.

**Comment by flit** [comment]
Good catch! Thanks for reporting it.
