### ISSUE TITLE
Mem-AP: add option to provide base address

### ISSUE THREAD

**Issue by 0xc0170** [mbedmicro/pyOCD#774]
I've received MCU that has invalid base address stored in BASE register. To be specific, I created yesterday an issue where address read is 0 and would traceback in ROMTable. This traceback led us to explore why there is 0.  BASE register reading returns invalid address, it is 0. But MCU has it at 0xe00fe000 for a specific AP (this is what we need to configure - we define AP via `find_aps`). For a specific AP, we need to set base address.

This is the request to add MEM-AP base address to pyOCD override, be able to provide the values to pyOCD. As result, it would skip reading `AP_BASE` , use provided values instead.

This currently blocks one of the targets we are working on.

cc @flit

**Comment by 0xc0170** [comment]
Looking at the `CoreSightTarget` class, it contains list of aps (their numbers). As it is list, would it make sense to transform to an object that can hold more than just a number of AP? Each AP could have a debug base address defined.

**Comment by flit** [comment]
Related to #769.

**Comment by flit** [comment]
For the short term, it's not too hard to use a customized init sequence to accomplish this task. (That's one major reason why the named init sequences exist.)

Basically, in the target class (subclass of `CoreSightTarget`) you need to modify the standard init sequence to insert an init task before the `find_components` task that fixes the `rom_addr` attribute of each AP. At the point this new task runs, the APs will have been identified and instantiated, and their `init()` methods called. But the ROM tables have not been read yet, so you can correct the ROM table base address.

```py
    def create_init_sequence(self):
        seq = super(xxx, self).create_init_sequence()
        seq.insert_before('find_components', self._fixup_ap_base_addrs)
        return seq

    def _fixup_ap_base_addrs(self):
        self.dp.aps[0].base_addr = 0xe00fe000
        # fix other APs here…
```

Of course, this isn't tested, but it _should_ work. 😄 

See a class such as `pyocd.target.builtin.target_CY8C64xx.cy8c64xx` for a more complete example of a target class that overrides `create_init_sequence()` to modify the init tasks. This class uses a replacement `find_aps` task to set the DP's `valid_aps` list to a fixed selection of APs. (And to create a custom `CortexM` subclass for each core.)

**Comment by 0xc0170** [comment]
Yes, it works 👍  Thanks, will close this as resolved.

For anyone who has a similar issue, I'll paste here the code for reference:

```
    def create_init_sequence(self):
        seq = super(TargetNameClass, self).create_init_sequence()
        seq.replace_task('find_aps', self.find_aps)
        # after creating ap, we fix rom addr
        seq.insert_before('init_ap_roms',
            ('fixup_ap_base_addrs', self._fixup_ap_base_addrs),
            )
        return seq

    def _fixup_ap_base_addrs(self):
        self.dp.aps[self.AP_NUM].rom_addr = 0xe00fe000

    def find_aps(self):
        if self.dp.valid_aps is not None:
            return

        self.dp.valid_aps = (self.AP_NUM,)
```
