### ISSUE TITLE
Flash_lpc1768.flash_algo has no key 'pc_erase_sector'

### ISSUE THREAD

**Issue by awelkie** [mbedmicro/pyOCD#85]
When running basic_test.py, `flash.erasePage` is called, which attempts to access the `pc_erase_sector` key of Flash_lpc1768.flash_algo (line 88 of flash.py), which does not exist and a `KeyError` exception is raised.

**Comment by c1728p9** [comment]
I have a patch that should fix the remaining LPC targets (lpc11u24, lpc1768 and lpc800):
https://github.com/c1728p9/pyOCD/commit/c590a0241c2eb73a196c3a48b79d7d8a233312b2

I tested this on the lpc11u24 and the lpc800, but have not tested it on the lpc1768.  I just got the lpc11u24 and lpc800 along with some other new boards on Friday :smile:.  If you have time could you try running basic_test.py on it?

Also, for this fix to truly be correct I think the flash algorithm will need to be rebuilt.  Right now the sector size is different between sector programming and sector erasing.  The program size is adjustable to so it can be modified to match the erase size in interface/flash_algo_mdk/LPC_IAP/FlashPrg.c in the CMSIS-DAP project.

**Comment by 0xc0170** [comment]
This was fixed
