### ISSUE TITLE
K64F flash algorithm is unstable

### ISSUE THREAD

**Issue by bremoran** [mbedmicro/pyOCD#88]
I'm not sure "unstable" is the right word. Maybe "unusable" would be more appropriate.  I've now spent days attempting to debug my project, chasing a Heisenbug, only to discover that it has absolutely nothing to do with my code.  Oh, goody.

Here's an example of the problem.
A good flash:
```
(gdb) x/16hx 0x5950
0x5950 <udp_sendto_chksum+80>:	0xb25b	0x4618	0x3718	0x46bd	0xbd80	0xbf00	0xb580	0xb088
0x5960 <udp_sendto_if+4>:	0xaf04	0x60f8	0x60b9	0x607a	0x807b	0x887b	0x69ba	0x9200
```
A bad flash:
```
(gdb) x/16hx 0x5950
0x5950 <udp_sendto_chksum+80>:	0xb25b	0x4618	0x3718	0x46bd	0xbd80	0xbf00	0xb580	0xff88
0x5960 <udp_sendto_if+4>:	0xaf04	0x60f8	0x60b9	0x607a	0x807b	0x887b	0x69ba	0x9200
```
The relevant part is 0x595e:
```
(gdb) disassemble 0x595e,+4
Dump of assembler code from 0x595e to 0x5962:
=> 0x0000595e <udp_sendto_if+2>:			; <UNDEFINED> instruction: 0xff88af04
```
This is... problematic.  It's not even entire sections which are broken, just individual bytes which are erased, but not programmed.

I haven't been able to work out a pattern in which bytes fail to be written correctly.

**Comment by c1728p9** [comment]
Hi @bremoran were you able to get this working?  I have been using the K64F lately and haven't had any trouble flashing.

**Comment by bremoran** [comment]
I'll have to check my pyOCD version, but this is still a constant problem.

**Comment by bremoran** [comment]
Under the latest version of pyOCD, this bug seems to be fixed.  However, the gdb load command now causes pyOCD to crash.  I'll file a new ticket.

**Comment by bremoran** [comment]
This issue has just recurred.  It seems more stable, but it still fails sometimes.

**Comment by c1728p9** [comment]
What kind of failure are you seeing?  An exception when loading code, corrupt flash or something else?  If it is an exception can you attach the call stack?

**Comment by bremoran** [comment]
I think it was corrupt flash, but it has now only occurred once in about 30 loads, so I'm not confident that it is not instability in some initialisation code.

**Comment by c1728p9** [comment]
Next time you see problems could you try dumping flash contents with something similar to the script below and then comparing to the original binary?
```
import pyOCD
from pyOCD.board import MbedBoard

filename = "dump.bin"
print "Dumping to file %s" % filename
with MbedBoard.chooseBoard(frequency = 10000000) as board:
    data = board.target.readBlockMemoryUnaligned8(0x0, 1024 * 1024)
    data = bytearray(data)
    with open(filename, "wb") as f:
        f.write(data)
    board.uninit()
    print("Dump finished")
```

**Comment by c1728p9** [comment]
If it works for your version of GDB, could you try the compare-sections command next time you see this?  If the contents differ from what you loaded then you might want to dump with the above script and compare.  If you see any pattern (or could send the differing binaries to me) I could take a look and try and fix whatever is going wrong.

**Comment by c1728p9** [comment]
Hi @bremoran , have you seen this issue occur lately?

**Comment by c1728p9** [comment]
Have you been able to recreate this issue @bremoran ?

**Comment by bremoran** [comment]
I did manage to reproduce, but I haven't seen in in a little while.  I suggest closing.  I will reopen if I hit it again.
